# Site settings
title: Natalia Soares
# description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
#url: "localhost:4000" # the base hostname & protocol for your site e.g.
url: https://natalianrs.github.io
baseurl: ""

# User settings
username: Natalia Soares
user_title: Natalia Soares
email: natalia.soaresnr@gmail.com
github_username: natalianrs
linkedin_username: natalianrs

hello:
  en: Hello 👋, I'm 
  pt: Olá 👋, eu sou


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

plugins:
  - jekyll-polyglot
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

languages: ["en", "pt"]
default_lang: "en"
exclude_from_localization: ["assets"]
parallel_localization: false

enable_darkmode: true 